apiVersion: v1
kind: PersistentVolume
metadata:
  name: docktex-volume
  labels:
    type: local
    app: docktex
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/docktex/executions