apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docktex-volume-claim
  labels:
    app: docktex
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi